nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^http://localhost:[0-9]+$']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['^http://localhost:[0-9]+$']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            expose_headers: ['Link']
            max_age: 3600
